spring:
  config:
    activate:
      on-profile: prod
    import: optional:configserver:http://config-service:8888
  # rabbitmq settings
  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: guest
    password: guest
  # DB settings
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://auth-db-service:3306/auth-service
    username: root
    password: 11111111
  redis:
    cluster:
      nodes: redis-cluster-0.redis-cluster.prod.svc.cluster.local:6379,redis-cluster-1.redis-cluster.prod.svc.cluster.local:6379,redis-cluster-2.redis-cluster.prod.svc.cluster.local:6379,redis-cluster-3.redis-cluster.prod.svc.cluster.local:6379,redis-cluster-4.redis-cluster.prod.svc.cluster.local:6379,redis-cluster-5.redis-cluster.prod.svc.cluster.local:6379
      max-redirects: 3
    password:
  zipkin:
    base-url: http://zipkin-service:9411/
    enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    # 기본적으로 유레카는 '호스트 이름'으로 접속하는 서비스를 레지스트리에 등록 -> 로컬(localhost)
    # 따라서 쿠버네티스, 도커와 같이 임의의 호스트 이름을 가지는 경우는 false로 하면 클라이언트를 인식하지 못한다.
    prefer-ip-address: true

endpoint:
  member-service: http://member-service:8080
